name: E2E

on:
    push:
        branches:
            - trunk
    pull_request:

jobs:
    E2E:
        runs-on: ubuntu-latest
        container: shopware/development:7.4-composer-2
        continue-on-error: true
        strategy:
            matrix:
                test-directory:
                    - "cypress/e2e/administration/settings/**/*"
                    - "cypress/e2e/administration/catalogue/**/*,cypress/e2e/administration/media-marketing/**/*,cypress/e2e/administration/customer/**/*"
                    - "cypress/e2e/administration/content/**/*,cypress/e2e/administration/general/**/*,cypress/e2e/administration/order/**/*,cypress/e2e/administration/rule-product-stream/**/*"
                    - "cypress/e2e/storefront/**/*"
        env:
            SHOPWARE_HTTP_CACHE_ENABLED: 0
            APP_ENV: e2e
            CYPRESS_baseUrl: http://localhost:8000
            CYPRESS_localUsage: 1
            DATABASE_URL: mysql://root:root@database:3306/root
            APP_URL: http://localhost:8000
            APP_SECRET: devsecret
            SHOPWARE_ES_HOSTS: elasticsearch:9200
            BLUE_GREEN_DEPLOYMENT: 1

        services:
            database:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: root

        steps:
            -   name: Clone platform
                uses: actions/checkout@v2

            -   name: Install Shopware
                run: |
                    composer run setup
                    composer run init:e2e
                    composer run e2e:prepare
                    chown -R application:application .
                    export WEB_DOCUMENT_ROOT=$(pwd)/public
                    /entrypoint supervisord > /dev/null 2>&1 &
            -   name: Cypress run
                run: |
                    composer run e2e:cypress -- run --browser chrome --spec "${{ matrix.test-directory }}" --headless
            -   uses: actions/upload-artifact@v2
                if: failure()
                with:
                    name: cypress
                    path: |
                        var/log
